### PR TITLE
Fix ordering with concurrent requests

### LINKED ISSUE #16: Output symbols have incorrect order
Ordering is seemingly random, probably due to concurrency. The order should retain the story order in `story2sketch.config.js`.

### PR DESCRIPTION
**Pull request by danielheyman**
Fixes #16

### CODE REVIEW

**Comment by danielheyman** [comment]
@chrisvxd Good catch. Pushed the changes.

File: src/server/Story2sketch.js [hunk 1]
```diff
@@ -245,20 +267,7 @@ export default class Story2sketch {
...
-
-      for (const symbol of symbols) {
-        symbol.frame.x = xOffset;
-        this.sketchPage.layers.push(symbol);
-      }
-
-      xOffset += this.widestByViewport[id] + this.symbolGutter;
-    }
-
-    fs.writeFileSync(this.output, JSON.stringify(this.sketchPage));
```
Comment (chrisvxd) [inline src/server/Story2sketch.js]: We still need this line in here, below the `this.positionSymbols()`
